### ISSUE TITLE
Issue with API version

### ISSUE THREAD

**Issue by diego-paired** [RevenueCat/firestore-revenuecat-purchases#29]
We've just tried installing the extension and setting it up on Firebase and RevenueCat, unfortunately the Cloud Function is throwing the following error:

```
InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.1, Api version: 0.1.0. Please retry the request with the correct version
```

We have contacted RevenueCat support but this might be faster, thanks.

**Comment by alfondotnet** [comment]
Hi @diego-paired,

Thanks for bringing up this issue. The backend should be able to update the version automatically. While we look into it, I have upgraded the version for you.

Could you let me know if it's now working?

**Comment by diego-paired** [comment]
@alfondotnet all working now, thanks
