### ISSUE TITLE
Install on an existing project with existing user collection

### ISSUE THREAD

**Issue by cyrildiagne** [RevenueCat/firestore-revenuecat-purchases#30]
Hello,

We are very excited to migrate our project to this extension.
We have an existing user collection that we've manually synced using RevenueCat hooks.

Is there a way to make this extension create a new collection with historical data?

**Comment by i14h** [comment]
Hi Cyril, Firebaser here. On our side we are working on a backend feature that allows extensions to backfill data after install, but I guess atm the best bet here would be something similar to what [Algolia extension](https://github.com/algolia/firestore-algolia-search/blob/main/functions/src/import/index.ts) or [BigQuery extension](https://github.com/firebase/extensions/tree/next/firestore-bigquery-export#backfill-your-bigquery-dataset) does, which is providing a script to be manually run on your data

**Comment by cyrildiagne** [comment]
Hello, thanks a lot for the feedback. That feature would be awesome! We'll looking into manually backfill the data in the meantime.

**Comment by vargajacint** [comment]
Hello, I have a simular issue. I have an existing project with existing customers. After install this extension, I get only the new customers "purchase info".  Any progress?
