### ISSUE TITLE
Save data to sub collection

### ISSUE THREAD

**Issue by vargajacint** [RevenueCat/firestore-revenuecat-purchases#34]
Hi,
First of all let me allow to say thank you for this extension. 
My problem is, I have an existing **users** collection, and I would like to save the incoming "purchase info", to a sub collection inside of the **users** collection. Is it possible?

**Comment by snehsagarajput** [comment]
I think you can fork the project and do the changes as per your preference. Because I can see that the requirements you are having can't be directly fulfilled as per current structure of the code/extension.

_`Fork -> Change Document Path -> Deploy the cloud function -> Add URL/Endpoint to Revenuecat Webhook.`_

**Comment by alfondotnet** [comment]
@vargajacint thanks for reaching out!
I think this request makes a lot of sense! To be honest, TIL about sub-collections 😅.

Would something like a boolean configuration parameter (Store Customer info as Subcollection) suffice for your use case?
If enabled, then we would always store our `purchase info` as a subcollection in the "customers collection" you specify.

**Comment by vargajacint** [comment]
@alfondotnet I think it's easier and more scaleable to make a wildcardish solution.
For example: `users/{userId}/subcollection` (it could be infinite deep).

<img width="434" alt="Screenshot 2022-08-06 at 8 58 47" src="https://user-images.githubusercontent.com/42407460/183238284-ecb19ab4-a49f-4ecd-822c-1e9579c9dfdd.png">

**Comment by alfondotnet** [comment]
That solution makes sense. 

You'd still not be able to configure the document name itself and end up with a document called `{id}` under `users/{id}/subcollection`, but I think that can be explored at a later time
