### ISSUE TITLE
Documentation error: Firestore rules configuration typo

### ISSUE THREAD

**Issue by dan-wu-open** [RevenueCat/firestore-revenuecat-purchases#41]
Hey, I have the extension setup. Really excited to use this data in our analytics and provide some auditability to our system! Thank you so much y'all.

Just noticed a small typo in the documentation
```
    match /revcatEvents/{id} {
      allow read: if request.auth.uid == resource.app_user_id
    }
```

`app_user_id` is not on `resource`, but on `resource.data`
```
    match /revcatEvents/{id} {
      allow read: if request.auth.uid == resource.data.app_user_id
    }
```

**Comment by alfondotnet** [comment]
Thanks for pointing this out @dan-wu-open , will route to the team.
