### ISSUE TITLE
"Invalid API Version" - Firebase extension not working

### ISSUE THREAD

**Issue by maurim96** [RevenueCat/firestore-revenuecat-purchases#48]
As the title describes, despite having followed the steps provided in the guide, I am facing this error while trying to integrate RevenueCat with Firebase Extension.

**'Integration Events' inside Integrations: Firebase RC page.**

<img width="899" alt="Screenshot 2023-02-17 at 16 10 56" src="https://user-images.githubusercontent.com/22548752/219770784-528726b7-708d-4484-9938-dc351bcb1643.png">

**Log error in Google Cloud Function**

`{
  "insertId": "63efd2af000ed715c29f136c",
  "jsonPayload": {
    "message": "InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.6, Api version: 0.1.1. Please retry the request with the correct version\n    at Object.exports.validateApiVersion (/workspace/lib/validate-api-version.js:7:15)\n    at /workspace/lib/index.js:78:32\n    at cloudFunction (/workspace/node_modules/firebase-functions/lib/providers/https.js:50:16)\n    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:101:17\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
    "structuredData": true
  },
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "XXXXXXXXXXXXXXXX",
      "region": "us-east1",
      "function_name": "ext-firestore-revenuecat-purchases-handler"
    }
  },
  "timestamp": "2023-02-17T19:17:03.972565Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "uf86ohclle0u",
    "instance_id": "00c61b117c460a23461dc95017164e7129076e28320a903657b2dc4c4170662eb7123d5d8b2b483edf717eab2ce4c187fca912337c7cb8bde8"
  },
  "logName": "projects/XXXXXXXXXXXX/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/XXXXXXXXXXXX/traces/761a396eb898a1147d3c4f1406e02a91",
  "receiveTimestamp": "2023-02-17T19:17:04.308960451Z"
}`

P/s: I have set up two different RevenueCat projects, while one is working as expected, the other one throws this random error leading to many issues on our App side, as we really need this events to get registered in Firestore (to trigger then another GC Function).

**Comment by louna-akkad-arabee** [comment]
i have same issue
"InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.6, Api version: 0.1.1. Please retry the request with the correct version

**Comment by de-pot-op** [comment]
I am having the same issue!

**Comment by louna-akkad-arabee** [comment]
im having the error for 3 days now!! Extension version 0.1.6, Api version: 0.1.1. Please retry the request with the correct version
any one was able to fix ?

**Comment by alfondotnet** [comment]
Hi all, 

Currently looking at this, will update when I have more information.

**Comment by alfondotnet** [comment]
The issue was due to Firebase sometimes not returning a header which our backend used to upgrade the version automatically, so in certain situations, the function would constantly error out. To fix this I have:

- Published a new version (0.1.7) that makes sure that the current version is always returned
- New installs all go to the 0.1.7 version so hopefully there's even less chance for this to happen
- Gone into the existing integrations with failures and manually fixed them
