### ISSUE TITLE
Support for Node.js 18

### ISSUE THREAD

**Issue by alexantonica** [RevenueCat/firestore-revenuecat-purchases#65]
Description
While checking my GCP cloud functions I noticed this
<img width="933" alt="Screenshot 2023-11-01 at 03 01 37" src="https://github.com/RevenueCat/firestore-revenuecat-purchases/assets/8859023/78791915-edfb-4d12-83ad-775c796181ef">

Is supporting v18 coming soon?

Thank you

**Comment by jefago** [comment]
Hi @alexantonica , we will make sure to ship Node.js 18 support in time!

**Comment by vicfergar** [comment]
Hi @alexantonica, I'm glad to inform you that there is a [new version of the extension](https://extensions.dev/extensions/revenuecat/firestore-revenuecat-purchases) (0.1.12) that includes support for Node.js 18 😃

**Comment by appsgenie** [comment]
We tried to upgrade and during upgrade I got this error:
**Service account ext-firestore-revenuecat--dr0f already exists within project projects/project-name
that was during the upgrade of the extension.**

and then when an event occured, the logs are showing this now:
**InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.12, Api version: 0.1.7. Please retry the request with the correct version**
