### ISSUE TITLE
InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.12, Api version: 0.1.7.

### ISSUE THREAD

**Issue by JakubBatel** [RevenueCat/firestore-revenuecat-purchases#67]
Hello guys,

I've set up the extension and when I tested it (using Flutter on iOS) the payment (in sandbox mode) went fine but the handler cloud function failed with `InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.7, Api version: 0.1.6.`. Then I read about it in #51 so I checked out the version in Firebase and there was an update. So I updated the version and now I am getting `InvalidApiVersionError: The version of this extension is not the same. Extension version 0.1.12, Api version: 0.1.7.`. 

Any idea why is this happening and how to fix it on my end, if possible?

**Comment by JakubBatel** [comment]
@vicfergar Yes, somehow it fixed itself overnight. I tried the sandbox payment again and it just worked. No idea how is this possible or why it is happening, but it might be a good idea to at least mention it somewhere in the documentation.

**Comment by vicfergar** [comment]
It's actually in the docs 😄 https://www.revenuecat.com/docs/firebase-integration#invalidapiversionerror-the-version-of-this-extension-is-not-the-same

**Comment by appsgenie** [comment]
I am running into the same issue as mentioned [here](https://github.com/RevenueCat/firestore-revenuecat-purchases/issues/65#issuecomment-1808968522)
are you saying to wait longer and try again and it might work without errors?

**Comment by JakubBatel** [comment]
@appsgenie Basically yes, from what I found out it seems like the RevenueCat server calls the cloud function even when there is no purchase from time to time (it was tracked in logs) and in my opinion, this is some update call. There was exactly one call during the night when nobody was testing and the next morning it just worked on its own. So my guess is that this call was the thing that fixed the problem.

**Comment by appsgenie** [comment]
OK i see. hmm mine was during a purchase when it failed but also the first purchase after the upgrade. so maybe related to that. but I think it is working now as far as I can tell. just would feel safer understanding the cause.
